Added IMAGES option
keiranlovett/rss-feed-to-markdown pull request #6
Opened 2024-06-14 13:35 UTC by dalezak

- updated .`gitignore` to exclude `node_modules` and `package-lock.json`
- updated `README.md` to include `[ID]`, `[LINK]`, `[IMAGE]`, `[IMAGES]` in example
- updated `process.js` to parse `[IMAGES]`

2024-06-14 13:51 UTC, keiranlovett requested changes

2024-06-14 13:51 UTC, keiranlovett commented on process.js
> +  const image_types = ['image/png', 'image/jpeg', 'image/jpg', 'image/gif'];
Might be cleaner to define `image_types` at the top of the file. Buried here could cause slight confusion.

2024-06-15 05:55 UTC, keiranlovett commented
Looks good. To keep node_packages out of the repo but make the action usable GitHub recommends using vercel/ncc to generate a packaged single file, so your changes won’t be reflected in the GitHub Action until you use vercel/ncc to generate a new `dist/index.js`. Once that’s in I can merge :)

2024-06-15 15:42 UTC, dalezak commented
Oh yes, I was wondering that, running off by fork didn’t return IMAGES as expected.

2024-06-15 21:57 UTC, keiranlovett approved these changes

2024-06-15 21:57 UTC, merged